[package]
name = "cosmic-edit"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
env_logger = "0.10.0"
grep = "0.3.1"
ignore = "0.4.21"
lazy_static = "1.4.0"
log = "0.4.20"
patch = "0.7.0"
notify = "6.1.1"
#TODO: this is using gtk for file dialogues
rfd = { version = "0.12.0", optional = true }
serde = { version = "1", features = ["serde_derive"] }
tokio = { version = "1", features = ["process", "time"] }
# Extra syntax highlighting
syntect = "5.1.0"
two-face = "0.3.0"
# Internationalization
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.3.0"

[dependencies.cosmic-syntax-theme]
git = "https://github.com/pop-os/cosmic-syntax-theme"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text"
branch = "refactor"
features = ["syntect", "vi"]
#path = "../cosmic-text"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "winit"]
#path = "../libcosmic"

#TODO: clean up and send changes upstream
[dependencies.systemicons]
git = "https://github.com/jackpot51/systemicons"

[target.'cfg(unix)'.dependencies]
fork = "0.1"

[features]
default = ["rfd", "wgpu"]
wgpu = ["libcosmic/wgpu"]

[patch.crates-io]
smithay-client-toolkit = { git = "https://github.com/pop-os/client-toolkit", branch = "wayland-resize" }

[profile.release-with-debug]
inherits = "release"
debug = true
