[package]
name = "cosmic-edit"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.71"

[dependencies]
env_logger = "0.10.0"
grep = "0.3.1"
ignore = "0.4.21"
lexical-sort = "0.3.1"
log = "0.4.20"
patch = "0.7.0"
notify = "6.1.1"
serde = { version = "1", features = ["serde_derive"] }
tokio = { version = "1", features = ["process", "time"] }
# Extra syntax highlighting
syntect = "5.1.0"
two-face = "0.3.0"
# Internationalization
i18n-embed = { version = "0.14", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.7"
rust-embed = "8"

[dependencies.cosmic-syntax-theme]
git = "https://github.com/pop-os/cosmic-syntax-theme"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text"
features = ["syntect", "vi"]
#path = "../cosmic-text"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "winit"]

[dependencies.rfd]
version = "0.13.0"
default-features = false
features = ["tokio", "xdg-portal"]
optional = true

[dependencies.smol_str]
version = "0.2.1"
features = ["serde"]

#TODO: clean up and send changes upstream
[dependencies.systemicons]
git = "https://github.com/jackpot51/systemicons"

[target.'cfg(unix)'.dependencies]
fork = "0.1"

[features]
default = ["rfd", "wgpu"]
wgpu = ["libcosmic/wgpu"]

[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "faed98b" }

[profile.release-with-debug]
inherits = "release"
debug = true
