[package]
name = "cosmic-edit"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
env_logger = "0.10.0"
fontdb = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.20"
rfd = "0.12.0"
# Internationalization
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.3.0"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text"
branch = "vi-editor"
features = ["two-face", "vi"]
#path = "../cosmic-text"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
branch = "menu"
default-features = false
features = ["winit"]
#path = "../libcosmic"

[patch.crates-io]
smithay-client-toolkit = { git = "https://github.com/pop-os/client-toolkit", branch = "wayland-resize" }
